CREATE TABLE IF NOT EXISTS genders(
   id serial PRIMARY KEY,
   name VARCHAR (50) NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   deleted_at TIMESTAMP WITHOUT TIME ZONE
);